- name: create ssh user
  ansible.builtin.user:
    name: ansible
    shell: /bin/bash
    create_home: yes

- name: enable sudo access for new ansible user
  lineinfile:
    path: "/etc/sudoers.d/ansible"
    state: present
    create: yes
    line: "ansible ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'

- name: copy autorised ssh keys to new user
  ansible.posix.authorized_key:
    user: ansible
    state: present
    exclusive: true
    key: "{{ authorized_keys }}"

- name: disable Root Login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"
    state: present
    backup: yes

- name: restart ssh service
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Allow everything and enable UFW
  ufw:
    state: enabled
    policy: deny

- name: allow ssh for firewall
  ufw:
    rule: allow
    name: OpenSSH
