- name:  install and configure docker
  hosts : all
  remote_user: ansible
  vars :
    prometheus : "yes"
    grafana : "yes"
    caddy : "yes"

- name:  install and configure prometheus    
  hosts:  
    - name : install prometheus 
      become: yes
      import_role: 
         name: "setup/prometheus" 
      when: prometheus == "yes"        

- name:  install and configure  grafana   
  hosts:  
    - name : install grafana
      become: yes
      import_role: 
          name: "setup/grafana"
      when: grafana == "yes"

- name:  install and configure caddy
  hosts:  
    - name : install caddy
      become: yes
      import_role: 
          name: "setup/caddy"
      when: caddy == "yes"